runtime: custom
env: flexible

# Instance configuration
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.6

# Resources
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

# Network
network:
  forwarded_ports:
    - 8080

# Environment variables
env_variables:
  STREAMLIT_SERVER_PORT: "8080"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"